Repository AOSSIE-Org/Resonate, pull requests merged in 2023-10, with the labels that each got.

#148 feat: add identity disclosure functionality in pair chats
  lib/controllers/pair_chat_controller.dart
  lib/views/screens/pair_chat_screen.dart
Labels: enhancement, aip-2023, hacktoberfest

#154 Otp verification navigation bugs fixed
  lib/controllers/email_verify_controller.dart
  lib/views/screens/email_verification_screen.dart
Labels: bug, aip-2023, hacktoberfest-accepted

#172 migration: api endpoints to cloud functions
  lib/services/api/api_service.dart
  lib/services/api/room_api.chopper.dart
  lib/services/api/room_api.dart
  lib/services/api_service.dart
  lib/services/room_service.dart
  lib/utils/constants.dart
  pubspec.lock
  pubspec.yaml
Labels: aip-2023, migration

#142 docs: update readme file
  README.md
Labels: documentation, aip-2023

#167 fix: confirm password field persists value on navigation
  lib/views/screens/login_screen.dart
Labels: bug, good first issue

#161 feat: implemented dynamic theme switching functionality.
  lib/controllers/auth_state_controller.dart
  lib/controllers/tabview_controller.dart
  lib/main.dart
  lib/routes/app_pages.dart
  lib/routes/app_routes.dart
  lib/themes/choose_theme_bottom_sheet.dart
  lib/themes/theme_controller.dart
  lib/themes/themes.dart
  lib/utils/enums/themes_enum.dart
  lib/views/screens/email_verification_screen.dart
  lib/views/screens/landing_screen.dart
  lib/views/screens/login_screen.dart
  lib/views/screens/pair_chat_screen.dart
  lib/views/screens/pairing_screen.dart
  lib/views/screens/profile_screen.dart
  lib/views/screens/room_screen.dart
  lib/views/screens/settings_screen.dart
  lib/views/screens/signup_screen.dart
  lib/views/screens/splash_screen.dart
  lib/views/screens/tabview_screen.dart
  lib/views/widgets/no_connection_dialog.dart
  lib/views/widgets/pair_chat_dialog.dart
  lib/views/widgets/participant_block.dart
  lib/views/widgets/profile_avatar.dart
  lib/views/widgets/room_tile.dart
Labels: enhancement, design, hacktoberfest, hacktoberfest-accepted

#175 Enhancement/improve image path handling
  lib/controllers/auth_state_controller.dart
  lib/routes/app_pages.dart
  lib/views/screens/landing_screen.dart
  lib/views/screens/login_screen.dart
  lib/views/screens/settings_screen.dart
  lib/views/screens/signup_screen.dart
  lib/views/screens/tabview_screen.dart
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#179 docs: added contribution section
  README.md
Labels: documentation, good first issue, hacktoberfest, hacktoberfest-accepted

#184 Implemented Edit User Profile Feature
  ios/Runner/Info.plist
  lib/controllers/edit_profile_controller.dart
  lib/controllers/onboarding_controller.dart
  lib/routes/app_pages.dart
  lib/routes/app_routes.dart
  lib/services/appwrite_service.dart
  lib/themes/themes.dart
  lib/views/screens/edit_profile_screen.dart
  lib/views/screens/profile_screen.dart
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#187 docs: Added docs for community standards.
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/documentation_issue.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/PULL_REQUEST_TEMPLATE.md
  SECURITY.md
Labels: documentation, aip-2023, hacktoberfest, hacktoberfest-accepted

#189 fix: removed blank space from the user profile picture and removed overflow of email verification icon.
  lib/views/screens/profile_screen.dart
Labels: bug, design, hacktoberfest, hacktoberfest-accepted

#193 fix: Resolve typo mistake for landingThirdImage
  lib/utils/app_images.dart
Labels: bug, good first issue

#196 No room placeholder alignment fixed
  lib/views/screens/home_screen.dart
Labels: bug

#199 Solved Missing Redirect Url Error (for both platforms)
  android/app/src/main/AndroidManifest.xml
Labels: bug, hacktoberfest, hacktoberfest-accepted

#205 docs: description for store listing
  docs/store_listing/description.md
Labels: documentation, good first issue

#176 feat: password strength checker
  lib/controllers/password_strength_checker_controller.dart
  lib/utils/colors.dart
  lib/views/screens/login_screen.dart
  lib/views/screens/signup_screen.dart
  lib/views/widgets/password_strength_indicator.dart
Labels: enhancement

#206 fix: text overflow in onboarding screen
  lib/views/screens/onboarding_screen.dart
Labels: bug, good first issue

#204 Added logic to delete old profile image as user add new profile image
  lib/controllers/auth_state_controller.dart
  lib/controllers/edit_profile_controller.dart
  lib/controllers/onboarding_controller.dart
Labels: enhancement
