Repository AOSSIE-Org/Resonate, pull requests merged in 2023-09, with the labels that each got.

#115 Enhanced App UI Sizes Organization
  assets/fonts/Montserrat-Regular.ttf
  assets/images/timer.svg
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  lib/controllers/auth_state_controller.dart
  lib/controllers/authentication_controller.dart
  lib/controllers/create_room_controller.dart
  lib/controllers/email_verify_controller.dart
  lib/controllers/single_room_controller.dart
  lib/main.dart
  lib/services/api/api_service.dart
  lib/utils/colors.dart
  lib/utils/constants.dart
  lib/utils/ui_sizes.dart
  lib/views/screens/create_room_screen.dart
  lib/views/screens/discussions_screen.dart
  lib/views/screens/email_verification_screen.dart
  lib/views/screens/login_screen.dart
  lib/views/screens/onboarding_screen.dart
  lib/views/screens/pair_chat_screen.dart
  lib/views/screens/pairing_screen.dart
  lib/views/screens/profile_screen.dart
  lib/views/screens/room_screen.dart
  lib/views/screens/signup_screen.dart
  lib/views/screens/splash_screen.dart
  lib/views/screens/tabview_screen.dart
  lib/views/widgets/custom_card.dart
  lib/views/widgets/no_connection_dialog.dart
  lib/views/widgets/pair_chat_dialog.dart
  lib/views/widgets/participant_block.dart
  lib/views/widgets/profile_avatar.dart
  lib/views/widgets/room_tile.dart
  pubspec.lock
  pubspec.yaml
Labels: design

#129 ux : fixed textfield appearance on validation error
  lib/views/screens/login_screen.dart
  lib/views/screens/signup_screen.dart
Labels: design, aip-2023

#134 feat: retry failed api requests
  lib/services/api/room_api.dart
Labels: enhancement, aip-2023

#132 feat: Starting point of app with Landing screens
  assets/images/landing_first.png
  assets/images/landing_second.png
  assets/images/landing_third.png
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  lib/controllers/auth_state_controller.dart
  lib/main.dart
  lib/routes/app_pages.dart
  lib/routes/app_routes.dart
  lib/views/screens/landing_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: design, aip-2023

#140 fix : Navigation to previous screen avoided after signing out
  lib/controllers/auth_state_controller.dart
Labels: bug, aip-2023

#131 refactor : optimize Appwrite Client instantiation
  lib/controllers/auth_state_controller.dart
  lib/controllers/pair_chat_controller.dart
  lib/controllers/rooms_controller.dart
  lib/controllers/single_room_controller.dart
  lib/services/appwrite_service.dart
Labels: enhancement, aip-2023

#139 feat: Assigning moderators for the room
  lib/controllers/single_room_controller.dart
  lib/views/widgets/participant_block.dart
Labels: enhancement, aip-2023
