Repository AOSSIE-Org/Resonate, pull requests merged in 2023-08, with the labels that each got.

#95 Replaced userEmail with appwrite UID
  lib/controllers/create_room_controller.dart
  lib/controllers/rooms_controller.dart
  lib/services/api/api_service.dart
  lib/services/room_service.dart
Labels: enhancement, gsoc

#85 Implemented Email Verifications
  lib/bindings/tabview_binding.dart
  lib/controllers/auth_state_controller.dart
  lib/controllers/authentication_controller.dart
  lib/controllers/onboarding_controller.dart
  lib/main.dart
  lib/routes/app_pages.dart
  lib/routes/app_routes.dart
  lib/utils/constants.dart
  lib/views/screens/create_room_screen.dart
  lib/views/screens/email_verification_screen.dart
  lib/views/screens/home_screen.dart
  lib/views/screens/login_screen.dart
  lib/views/screens/onboarding_screen.dart
  lib/views/screens/profile_screen.dart
  lib/views/screens/room_screen.dart
  lib/views/screens/signup_screen.dart
  lib/views/screens/splash_screen.dart
  lib/views/screens/tabview_screen.dart
  lib/views/widgets/room_tile.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement

#101 Integrated LiveKit WebRTC for Audio Communication
  android/app/src/main/AndroidManifest.xml
  ios/Podfile
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/Info.plist
  lib/controllers/livekit_controller.dart
  lib/controllers/rooms_controller.dart
  lib/controllers/single_room_controller.dart
  lib/services/room_service.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, gsoc

#100 Added Visibilty toggle for Rooms to home screen.
  assets/images/no_room.png
  lib/views/screens/home_screen.dart
Labels: good first issue

#102 profile icon moved to appbar and minor errors corrected
  ios/Podfile.lock
  lib/bindings/tabview_binding.dart
  lib/controllers/create_room_controller.dart
  lib/controllers/onboarding_controller.dart
  lib/controllers/rooms_controller.dart
  lib/controllers/single_room_controller.dart
  lib/controllers/tabview_controller.dart
  lib/routes/app_pages.dart
  lib/routes/app_routes.dart
  lib/services/api/room_api.dart
  lib/services/room_service.dart
  lib/utils/colors.dart
  lib/utils/enums/signed_in_by.dart
  lib/views/screens/create_room_screen.dart
  lib/views/screens/discussions_screen.dart
  lib/views/screens/home_screen.dart
  lib/views/screens/profile_screen.dart
  lib/views/screens/room_screen.dart
  lib/views/screens/signup_screen.dart
  lib/views/screens/splash_screen.dart
  lib/views/screens/tabview_screen.dart
  lib/views/widgets/custom_card.dart
  lib/views/widgets/participant_block.dart
  lib/views/widgets/profile_avatar.dart
  lib/views/widgets/room_tile.dart
Labels: enhancement, good first issue

#106 Implemented Room Link Sharing and App Link Intent Handling
  android/app/src/main/AndroidManifest.xml
  lib/controllers/auth_state_controller.dart
  lib/controllers/rooms_controller.dart
  lib/controllers/tabview_controller.dart
  lib/main.dart
  lib/views/widgets/room_tile.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, gsoc

#107 Alert Screen for Internet Connectivity Status
  android/app/src/main/AndroidManifest.xml
  assets/images/no_connection.svg
  ios/Podfile.lock
  lib/bindings/auth_splash_bindings.dart
  lib/controllers/network_controller.dart
  lib/views/screens/home_screen.dart
  lib/views/widgets/no_connection_dialog.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, gsoc

#108 Enhanced Participant Sorting in Room Screen
  lib/controllers/single_room_controller.dart
Labels: enhancement, gsoc

#105 Made UI responsive
  lib/bindings/auth_splash_bindings.dart
  lib/bindings/tabview_binding.dart
  lib/controllers/auth_state_controller.dart
  lib/controllers/authentication_controller.dart
  lib/controllers/email_verify_controller.dart
  lib/controllers/network_controller.dart
  lib/controllers/onboarding_controller.dart
  lib/main.dart
  lib/utils/ui_sizes.dart
  lib/views/screens/create_room_screen.dart
  lib/views/screens/email_verification_screen.dart
  lib/views/screens/home_screen.dart
  lib/views/screens/login_screen.dart
  lib/views/screens/onboarding_screen.dart
  lib/views/screens/profile_screen.dart
  lib/views/screens/room_screen.dart
  lib/views/screens/signup_screen.dart
  lib/views/screens/tabview_screen.dart
  lib/views/widgets/custom_card.dart
  lib/views/widgets/participant_block.dart
  lib/views/widgets/room_tile.dart
  pubspec.yaml
Labels: enhancement, design

#112 Include Appwrite JWT token in API requests
  lib/controllers/auth_state_controller.dart
  lib/controllers/single_room_controller.dart
  lib/services/api/room_api.dart
Labels: enhancement, gsoc

#113 UI/UX Enhancements + Minor Bug Fixes
  ios/Podfile.lock
  lib/controllers/auth_state_controller.dart
  lib/utils/constants.dart
  lib/views/screens/create_room_screen.dart
  lib/views/screens/profile_screen.dart
  lib/views/screens/room_screen.dart
  lib/views/screens/tabview_screen.dart
  lib/views/widgets/participant_block.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, design, gsoc

#119 Fixed known issues + Improved UX
  lib/controllers/rooms_controller.dart
  lib/controllers/single_room_controller.dart
  lib/services/room_service.dart
Labels: bug, gsoc
