Repository AOSSIE-Org/Resonate, pull requests merged in 2024-03, with the labels that each got.

#291 [BugFix] Fix for Null Check Operator Used on a Null Value Exception in UiSizes Class
  android/app/build.gradle
  android/build.gradle
  android/settings.gradle
  lib/main.dart
  lib/utils/ui_sizes.dart
  lib/views/screens/create_room_screen.dart
  lib/views/screens/tabview_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: bug, enhancement

#282 [FEATURE] Implement Dynamic Theming for User-Selected App Color
  lib/controllers/auth_state_controller.dart
  lib/controllers/authentication_controller.dart
  lib/controllers/create_room_controller.dart
  lib/controllers/edit_profile_controller.dart
  lib/controllers/network_controller.dart
  lib/controllers/rooms_controller.dart
  lib/main.dart
  lib/themes/choose_theme_bottom_sheet.dart
  lib/themes/theme_controller.dart
  lib/themes/themes.dart
  lib/views/screens/create_room_screen.dart
  lib/views/screens/discussions_screen.dart
  lib/views/screens/edit_profile_screen.dart
  lib/views/screens/email_verification_screen.dart
  lib/views/screens/home_screen.dart
  lib/views/screens/login_screen.dart
  lib/views/screens/pair_chat_screen.dart
  lib/views/screens/pairing_screen.dart
  lib/views/screens/profile_screen.dart
  lib/views/screens/room_screen.dart
  lib/views/screens/signup_screen.dart
  lib/views/screens/tabview_screen.dart
  lib/views/widgets/color_selection_widget.dart
  lib/views/widgets/discussion_tile.dart
  lib/views/widgets/loading_widget.dart
  lib/views/widgets/no_connection_dialog.dart
  lib/views/widgets/pair_chat_dialog.dart
  lib/views/widgets/participant_block.dart
  lib/views/widgets/profile_avatar.dart
  lib/views/widgets/room_tile.dart
  pubspec.lock
Labels: enhancement, design

#261 fix: prevent user credentials to persist on login screen after logout & provide UI feedback on short password entry
  lib/controllers/authentication_controller.dart
  lib/utils/constants.dart
  lib/views/screens/login_screen.dart
Labels: bug, enhancement

#254 feat: Implemented Forgot Password
  lib/controllers/authentication_controller.dart
  lib/routes/app_pages.dart
  lib/routes/app_routes.dart
  lib/services/appwrite_service.dart
  lib/views/screens/forgot_password_screen.dart
  lib/views/screens/login_screen.dart
  lib/views/screens/reset_password_screen.dart
Labels: enhancement
