Repository AOSSIE-Org/Resonate, pull requests merged in 2024-05, with the labels that each got.

#244 Fixed Black Screen issue
  lib/views/screens/splash_screen.dart
Labels: bug, attended, IMS

#269 [onboarding] trailing space username auth bug fix
  lib/views/screens/onboarding_screen.dart
Labels: attended, IMS

#290 Migrate to declarative plugin declaration from imperative plugin declaration
  android/app/build.gradle
Labels: attended, IMS

#294 Enhance]:Replace-deperacted-OnWillPopScope-with-PopScope
  lib/utils/utils.dart
  lib/views/screens/edit_profile_screen.dart
Labels: enhancement, good first issue, attended, IMS

#296 Handle overflow exception from profile screen
  lib/views/screens/profile_screen.dart
Labels: design, attended, IMS

#309 Fix textfield tag error
  lib/controllers/create_room_controller.dart
  lib/views/screens/create_room_screen.dart
  pubspec.lock
Labels: attended, IMS

#324 Fix: Make login screen responsive by using height value from UiSizes
  lib/views/screens/login_screen.dart
Labels: attended, IMS

#323 Fix: Set clip behavior to antiAlias in CustomCard widget to fix splash overflow
  lib/views/widgets/custom_card.dart
  pubspec.lock
Labels: design, attended, IMS

#195 fix: AuthenticationController-not-found
  .gitignore
  lib/controllers/pair_chat_controller.dart
  pubspec.lock
Labels: bug, help wanted, question

#213 Added: Check server status method added for the appwrite server before going to the home screen.
  lib/services/appwrite_service.dart
Labels: enhancement, attended

#297 #230 fix | used Theme to give dynamic colors
  lib/themes/themes.dart
  lib/views/screens/email_verification_screen.dart
  lib/views/screens/login_screen.dart
  lib/views/screens/profile_screen.dart
Labels: attended, intra
