Repository AOSSIE-Org/Resonate, pull requests merged in 2024-07, with the labels that each got.

#329 Brought Resonate to Stable State
  .gitignore
  ONBOARDING.md
  README.md
  android/app/src/main/AndroidManifest.xml
  devtools_options.yaml
  ios/Flutter/AppFrameworkInfo.plist
  ios/Podfile.lock
  lib/controllers/auth_state_controller.dart
  lib/controllers/authentication_controller.dart
  lib/controllers/change_email_controller.dart
  lib/controllers/create_room_controller.dart
  lib/controllers/discussions_controller.dart
  lib/controllers/edit_profile_controller.dart
  lib/controllers/email_verify_controller.dart
  lib/controllers/single_room_controller.dart
  lib/main.dart
  lib/routes/app_pages.dart
  lib/routes/app_routes.dart
  lib/services/api_service.dart
  lib/services/appwrite_service.dart
  lib/services/room_service.dart
  lib/utils/constants.dart
  lib/views/screens/change_email_screen.dart
  lib/views/screens/create_room_screen.dart
  lib/views/screens/edit_profile_screen.dart
  lib/views/screens/email_verification_screen.dart
  lib/views/screens/profile_screen.dart
  lib/views/screens/room_screen.dart
  lib/views/screens/signup_screen.dart
  lib/views/screens/splash_screen.dart
  lib/views/screens/tabview_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: gsoc

#330 fix: #247 added yaml file
  .github/WORK_FLOW/greet_contributors.yml
Labels: good first issue

#332 Midterm evaluation
  assets/svg/default_profile_picture.svg
  assets/svg/resonate_logo.svg
  assets/svg/resonate_logo_white.svg
  lib/controllers/auth_state_controller.dart
  lib/controllers/authentication_controller.dart
  lib/controllers/change_email_controller.dart
  lib/controllers/create_room_controller.dart
  lib/controllers/edit_profile_controller.dart
  lib/controllers/email_verify_controller.dart
  lib/controllers/onboarding_controller.dart
  lib/controllers/password_strength_checker_controller.dart
  lib/controllers/tabview_controller.dart
  lib/for_developers/text_theme.dart
  lib/for_developers/theme_color_model.dart
  lib/for_developers/theme_colors_page.dart
  lib/main.dart
  lib/models/resonate_user.freezed.dart
  lib/models/themes_model.dart
  lib/new_themes/new_theme.dart
  lib/new_themes/new_theme_screen_controller.dart
  lib/new_themes/theme_enum.dart
  lib/new_themes/theme_list.dart
  lib/new_themes/theme_screen.dart
  lib/routes/app_pages.dart
  lib/routes/app_routes.dart
  lib/themes/theme_controller.dart
  lib/utils/colors.dart
  lib/utils/constants.dart
  lib/utils/ui_sizes.dart
  lib/utils/utils.dart
  lib/views/new_screens/new_edit_profile_screen.dart
  lib/views/new_screens/new_email_verification_screen.dart
  lib/views/new_screens/new_forgot_password_screen.dart
  lib/views/new_screens/new_login_screen.dart
  lib/views/new_screens/new_onboarding_screen.dart
  lib/views/new_screens/new_profile_screen.dart
  lib/views/new_screens/new_settings_screen.dart
  lib/views/new_screens/new_signup_screen.dart
  lib/views/new_screens/new_welcome_screen.dart
  lib/views/new_screens/user_account_screen.dart
  lib/views/new_widgets/new_loading_dialog.dart
  lib/views/new_widgets/welcome_screen_dialog.dart
  lib/views/screens/change_email_screen.dart
  lib/views/screens/create_room_screen.dart
  lib/views/screens/delete_account_screen.dart
  lib/views/screens/edit_profile_screen.dart
  lib/views/screens/email_verification_screen.dart
  lib/views/screens/landing_screen.dart
  lib/views/screens/pair_chat_screen.dart
  lib/views/screens/pairing_screen.dart
  lib/views/screens/profile_screen.dart
  lib/views/screens/signup_screen.dart
  lib/views/screens/splash_screen.dart
  lib/views/widgets/color_selection_widget.dart
  lib/views/widgets/discussion_tile.dart
  lib/views/widgets/password_strength_indicator.dart
  lib/views/widgets/profile_avatar.dart
  pubspec.lock
  pubspec.yaml
Labels: design, gsoc
