Repository AOSSIE-Org/Resonate, pull requests merged in 2024-01, with the labels that each got.

#178 fix: Resolve split-screen issue #177
  lib/views/widgets/no_connection_dialog.dart
Labels: bug

#180 ui: improved pair chat screen
  lib/views/screens/pair_chat_screen.dart
  lib/views/widgets/pair_chat_dialog.dart
  pubspec.lock
Labels: enhancement, design

#251 ui: crop profile image screen improved
  android/app/src/main/AndroidManifest.xml
  lib/controllers/edit_profile_controller.dart
  lib/themes/themes.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement
