Repository AOSSIE-Org/Resonate, pull requests merged in 2025-09, with the labels that each got.

#522 Update README.md
  README.md
Labels: documentation, good first issue

#526 fix: Update Test Workflow triggers
  .github/workflows/run_tests.yml
Labels: bug, gsoc

#532 Feat: Added metadata to all keys and removed duplicate translations
  l10n.yaml
  lib/l10n/app_en.arb
  lib/l10n/app_hi.arb
  lib/l10n/app_localizations.dart
  lib/l10n/app_localizations_en.dart
  lib/l10n/app_localizations_hi.dart
  lib/views/screens/about_app_screen.dart
  lib/views/screens/add_chapter_screen.dart
  lib/views/screens/chapter_play_screen.dart
  lib/views/screens/edit_profile_screen.dart
  lib/views/screens/email_verification_screen.dart
  lib/views/screens/story_screen.dart
Labels: enhancement, good first issue

#540 feat: updated the UX issue
  lib/controllers/about_app_screen_controller.dart
  lib/controllers/auth_state_controller.dart
Labels: bug, good first issue

#550 feat: add Gujarati translation support
  ios/Runner/Info.plist
  lib/l10n/app_gu.arb
  lib/l10n/app_localizations_gu.dart
  lib/main.dart
  pubspec.yaml
Labels: enhancement, translations
