Repository AOSSIE-Org/Resonate, pull requests merged in 2025-08, with the labels that each got.

#499 fix: fixed workflow bug
  .github/workflows/update-project-structure.yml
Labels: bug, documentation

#500 Fix Greet Contributor Workflow
  .github/workflows/greet_contributors.yml
Labels: bug

#505 Setup CI/CD to automatically compile and deploy builds to Internal Testing on Google Play
  .github/workflows/store_deploy_android.yml
  ONBOARDING.md
  android/.gitignore
  lib/utils/constants.dart
  pubspec.yaml
Labels: enhancement, gsoc

#506 Updated the action to tag Contributors
  .github/workflows/greet_contributors.yml
Labels: bug

#509 Partial Implementation for Automated Software Tests
  .github/workflows/run_tests.yml
  .github/workflows/store_deploy_android.yml
  android/build/.last_build_id
  lib/controllers/auth_state_controller.dart
  lib/controllers/change_email_controller.dart
  lib/controllers/create_room_controller.dart
  lib/controllers/edit_profile_controller.dart
  lib/controllers/explore_story_controller.dart
  lib/models/resonate_user.freezed.dart
  lib/models/resonate_user.g.dart
  test/controllers/auth_state_controller_test.dart
  test/controllers/auth_state_controller_test.mocks.dart
  test/controllers/change_email_controller_test.dart
  test/controllers/change_email_controller_test.mocks.dart
  test/controllers/chapter_player_controller_test.dart
  test/controllers/create_room_controller_test.dart
  test/controllers/create_room_controller_test.mocks.dart
  test/controllers/edit_profile_controller_test.dart
  test/controllers/edit_profile_controller_test.mocks.dart
  test/controllers/explore_story_controller_test.dart
  test/widget_test.dart
Labels: enhancement, gsoc

#512 Implement advanced Creator Interaction Functionality
  lib/controllers/auth_state_controller.dart
  lib/controllers/explore_story_controller.dart
  lib/controllers/user_profile_controller.dart
  lib/l10n/app_en.arb
  lib/l10n/app_hi.arb
  lib/l10n/app_localizations.dart
  lib/l10n/app_localizations_en.dart
  lib/l10n/app_localizations_hi.dart
  lib/models/follower_user_model.dart
  lib/models/follower_user_model.freezed.dart
  lib/models/follower_user_model.g.dart
  lib/models/resonate_user.dart
  lib/utils/constants.dart
  lib/views/screens/explore_screen.dart
  lib/views/screens/followers_screen.dart
  lib/views/screens/profile_screen.dart
  lib/views/widgets/filtered_list_tile.dart
  project_structure.txt
  test/controllers/change_email_controller_test.dart
  test/controllers/create_room_controller_test.dart
  test/controllers/edit_profile_controller_test.dart
  test/controllers/explore_story_controller_test.dart
  test/controllers/explore_story_controller_test.mocks.dart
  test/controllers/user_profile_controller_test.dart
  test/controllers/user_profile_controller_test.mocks.dart
Labels: enhancement, gsoc

#513 Add Configuration for OAuth to work with workflows
  .github/workflows/store_deploy_android.yml
  android/app/build.gradle.kts
  android/app/src/main/AndroidManifest.xml
  lib/views/screens/welcome_screen.dart
  pubspec.yaml
Labels: gsoc

#515 Fix: backend repo links in onboarding document
  ONBOARDING.md
Labels: documentation
